name: build test
run-name: Build Test with GitHub Actions
on: [push]
jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: install Python via uv
        run: /bin/sh ./install_python_uv.sh
      - name: build dependency
        run: /bin/sh ./build_deps.sh
